### ISSUE TITLE
CI fails with Bazel@HEAD due to missing java_runtime

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_appengine#119]
CI for rules_appengine is failing with Bazel@HEAD
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1838#d8060cf3-3da6-491f-8598-92312e044b19

```
(02:09:50) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/78942d9c203732b140720053b958a9bd/external/rules_appengine_toolchain/BUILD.bazel:9:23: @rules_appengine_toolchain//:jdk8: missing value for mandatory attribute 'java_runtime' in 'java_toolchain' rule
--
  | (02:09:50) ERROR: /var/lib/buildkite-agent/builds/bk-docker-p58c/bazel-downstream-projects/rules_appengine/appengine/BUILD:15:6: Target '@rules_appengine_toolchain//:jdk8' contains an error and its package is in error and referenced by '//appengine:jdk8'
```

This originates from a change introduced in https://github.com/bazelbuild/bazel/commit/c8e179fc7676ec8c0f4787d470b51e9837fc9750

This made `java_runtime` a mandatory attribute of `java_toolchain`.

**Comment by comius** [comment]
I'll investigate, since I provided a recent PR https://github.com/bazelbuild/rules_appengine/pull/118, that was supposed to fix this.

**Comment by comius** [comment]
@pmbethe09 I have a question regarding rules_appengine. In downstream testing we have an Ubuntu 18.04 which has only Java 11 available. If I constrain the JDK toolchain to local JDK version 8, the downstream test fail on that system. See
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1844#84edc451-cd35-4a6a-9500-02f8d76a093e

This seems to be the proper behaviour and my best guess is Ubuntu 18.04 should be removed from CI for rules_appengine. I'm concluding this, because it only supports war archives which are Java 8. Java 11 supposedly needs jars.

Alternative to this is to test just the python part of rules_appengine on Ubuntu 18.04, but this seems weird.

I also have wrong solution, which ignores JDK version and the downstream build still passes. I'd rather do the right thing.

**Comment by pmbethe09** [comment]
I will take a look at this -- have been tied up with other things until now.

**Comment by comius** [comment]
friendly ping, do I remove Ubuntu 18.04 with Java 11 from continuous integration or is there a way that is should somehow produce the correct results?

**Comment by pmbethe09** [comment]
I guess remove for now -- I am just not sure what to do here.

**Comment by comius** [comment]
> I guess remove for now -- I am just not sure what to do here.

There is another alternative. We could add remote_jdk8 to Bazel. This would certainly make rules_appengine's ride smoother for potentially a lot of user.

@lberki, @cushon What do you think about adding remote_jdk8 to Bazel? Was it once already in and removed? Or are there any other issues with that?

**Comment by lberki** [comment]
I don't have any objections in principle to addint remote_jdk8 to jdk.WORKSPACE (I suppose that's what you mean...), but:

1. What's the benefit of keeping the Ubuntu 18.04 builds with rules_appengine?
2. The same effect could be achieved by adding remote_jdk8 to the WORKSPACE file of rules_appengine, which looks like a more targeted approach.

**Comment by comius** [comment]
> I don't have any objections in principle to addint remote_jdk8 to jdk.WORKSPACE (I suppose that's what you mean...), but:
> 
> 1. What's the benefit of keeping the Ubuntu 18.04 builds with rules_appengine?

The benefit is keeping users of rules_appengine happy. They don't need to install JDK8 on their systems. There were previous complaints that system libraries get mixed up, this shouldn't happen with Java platformization changes. Failing build is actually a proof of that.

> 2. The same effect could be achieved by adding remote_jdk8 to the WORKSPACE file of rules_appengine, which looks like a more targeted approach.

Great suggestion. I'll only modify it a bit. Adding jdk8 repositories to rules_java and importing them in rules_appengine.
